version: '3.8'

services:
  frontend:
    build:
      context: ./feels-like-frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://node50.cs.colman.ac.il:4000
    ports:
      - "443:443"
    volumes:
      - ./ssl:/ssl
    environment:
      - PORT=443
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./feels-like-backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./ssl:/ssl
      - ./feels-like-backend/uploads:/app/uploads
      - ./feels-like-backend/.env:/app/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
